'use strict';
var translate = {
    ru:{
        settings:"Настройки",
        noFlashlight:'Устройство не поддерживает фонарик.',
        on:'Вкл',
        off:'Выкл',
        metres:'м',
        minutes:'м',
        hours:'ч',
        savedTitle:"Сохраненные",
        savedCodes:"Сохраненные коды",
        morseCode:"Коды Морзе",
        morseSignals:"Коды Морзе",
        latitude:"Долгота",
        longitude:"Широта",
        battery:"Батарея",
        height:"Высота",
        stroboscope:"Стробо<br/>скоп",
        screen:"Экран",
        morse:"Морзе",
        sos:"SOS",
        sounds:"Звук",
        morseSounds:"Звуки Морзе",
        brightnessControl:"Управлять яркостью",
        turnOnLaunch:"Фонарик при запуске",
        volume:"Громкость",
        displayBrightness:"Яркость экрана",
        flashlightBrightness:"Яркость фонарика",
        delete:"Удалить",
        morseLight:"Фонарик Морзе",
        morseTextareaPlaceholder:"Введите текст",
        ru:"Русский",
        en:"Английский"
    },
    en:{
        title:"Travel Flashlight",
        settings:"Settings",
        noFlashlight:'Flashlight not available!',
        on:'On',
        off:'Off',
        metres:'m',
        minutes:'m',
        hours:'h',
        savedTitle:"Saved",
        savedCodes:"Saved Codes",
        morseCode:"Morse Code",
        morseSignals:"Morse Signals",
        latitude:"Latitude",
        longitude:"Longitude",
        battery:"Battery",
        height:"Height",
        stroboscope:"Strobo<br/>scope",
        screen:"Screen",
        morse:"Morse",
        sos:"Sos",
        sounds:"Sounds",
        morseSounds:"Morse Sounds",
        brightnessControl:"Brightness Control",
        turnOnLaunch:"Turn Flash on Launch",
        volume:"Volume",
        displayBrightness:"Display Brightness",
        flashlightBrightness:"Flashlight Brightness",
        delete:"Delete",
        morseLight:"Light Morse",
        morseTextareaPlaceholder:"Input text here",
        ru:"Russian",
        en:"English"
    }
};

